### ISSUE TITLE
'could not find function "DevKidCC"' error

### ISSUE THREAD

**Issue by OlaBab** [KidneyRegeneration/DevKidCC#2]
Hi,

I'm new in using Rstudio and I'm trying to use DevKidCC to compare our single cell data against your library. It's a great idea creating it, thank you! I stumbled upon this particular problem:

> organoid <- DevKidCC(organoid)
Error in DevKidCC(organoid) : could not find function "DevKidCC"

I have double checked I have DevKidCC downloaded and the library unpacked, I don't know how to solve this issue.

Ola

**Comment by DavidB-XI** [comment]
Have you tried

library(DevKidCC)
organoid <- DevKidCC(organoid)

This works because you are required to load the library first (via the library function), even after unpacking it to a directory.

Let me know how it works -

David

**Comment by OlaBab** [comment]
I tried it now, the error is still the same:

> library(DevKidCC)
> organoid <- DevKidCC(organoid)
Error in DevKidCC(organoid) : could not find function "DevKidCC"

**Comment by DavidB-XI** [comment]
Another alternative is to use the library package devtools

library(devtools)

To directly install the library package (and not just unpack it!)
devtools::install_github("KidneyRegeneration/DevKidCC")

then you can use

library(DevKidCC)
organoid <- DevKidCC(organoid)

Does this work?

**Comment by OlaBab** [comment]
Unfortunately, the same:

> devtools::install_github("KidneyRegeneration/DevKidCC")
Skipping install of 'DevKidCC' from a github remote, the SHA1 (e2ba6bb4) has not changed since last install.
  Use `force = TRUE` to force installation
> force = TRUE
> library(DevKidCC)
> organoid <- DevKidCC(organoid)
Error in DevKidCC(organoid) : could not find function "DevKidCC"

**Comment by DavidB-XI** [comment]
I think it may be related to installing the local package incorrectly.

Try removing the package first (yes, this will remove your current DevKidCC package), and then reinstalling it

remove.packages("DevKidCC")
devtools::install_github("KidneyRegeneration/DevKidCC")

library(DevKidCC)
organoid <- DevKidCC(organoid)

**Comment by DavidB-XI** [comment]
Sorry, I have just tried it again, and this works for me:

remove.packages("DevKidCC")
devtools::install_github("KidneyRegeneration/DevKidCC")

library(DevKidCC)
data("organoid")
organoid <- DevKidCC::DKCC(organoid)

**Comment by OlaBab** [comment]
Thank you so much, this code worked in the end:

organoid <- DevKidCC::DKCC(organoid)

**Comment by DavidB-XI** [comment]
Great - I'm very interested in this work!

So if you need any help regarding methods and analysis of kidney / kidney organoid data, please let me know how it goes!
This is an open invitation to anyone who reads this as well - very interested in how your work includes DevKidCC or any other kidney based quantitative methods!
